language: node_js
node_js:
    - "6.9.0"
    - "8.5.0"

install:
    - npm install .
    - curl -sL -o ./kelda https://github.com/kelda/kelda/releases/download/dev/kelda_linux
        && chmod +x ./kelda

before_script:
    - npm install -g gulp-cli

script:
    - gulp lint test
    - mkdir -p ~/.kelda/infra/ && mv ./testInfra.js ~/.kelda/infra/default.js
    - ./kelda inspect ./haproxy.js graphviz
    - ./kelda inspect ./examples/haproxyExampleSingleApp.js graphviz
    - ./kelda inspect ./examples/haproxyExampleMultipleApps.js graphviz

notifications:
    slack:
        secure: Dvb+HsKF29Gpx9aSvz0xByhXEVo9oppgcoNcxYtZFlwdAzvUoKsng8j66BnhY+yNBaHPfDTC4OHdyCAjI0dCFg6Y2vVN8EfQit9n+howDMAmyiWTO28+O4JKDNg1RK7YsIDF7qSEMuFzid84wjgbPMdkgn7SXM4TjqDL5UbjsrBVNLdPpwIP+T066UTvqUp/r8KYQ5R/hAmmlf2PUoSvKQuZiJqdYE8L4zwGz9zuqiivi8NawhrTRyPIFT9yCKPBO+YJC9w/IFqq/XX88GiTB/2zTv/mFAgXbDKGQ/BNNbfljYqt72GCZQqBQZUeyxFYbm0YbsCTIwqIugjLn3+RuoC34Doj/ykPC6dBYMGGHvVrBvVPpQOpTFMunp2fKgCsLPWtwLJf1Pj+KgM8QrrC+sYoxcd23de5mhnrWOWklUkhcC91b56YJBeFLbukeHeXGmhMnOGjXYzW3wosUrJlsGQm3dbLuE4V+vZy5txJ5z3FerxVBCepZ0PfMJBsTJnnHIXIAPub2KBUHaxgdo6lUjwwPNO2gY5YifyJ+4N8iP0X30EGZJtKRgxUNB/A6kl2nEac7HIn1/DmBab1O1qijyLzNu3HfVIg4qClwKhZrPKXvTRGrp5K2oTXm+aD4HlEjHBUT/KfBhQb0WlFhae/clgH1quTSSyDNwqTslNs9IU=
